name: guide_liverpool
version: 1.13.0+44
publish_to: none
description: The Guide Liverpool app is a blog reader application for local news and updates in Liverpool
environment:
  sdk: ">=2.19.5 <3.0.0"
dependencies:
  analyzer: ^5.10.0
  another_flushbar: ^1.12.29
  app_tracking_transparency: ^2.0.3
  auto_route: ^6.0.5
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  charge_wallet_sdk: ^0.0.2
  chewie: ^1.3.2
  confetti: ^0.7.0
  collection: ^1.17.0
  country_code_picker: ^3.0.0
  decimal: ^2.3.0
  dio: ^5.1.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flex_color_scheme: ^7.0.1
  flutter_dotenv: ^5.0.0
  flutter_html: 3.0.0-alpha.6
  flutter_inappwebview: ^5.7.1
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_stripe: ^9.0.0+1
  flutter_svg: ^2.0.4
  flutter_udid: ^2.0.0
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^2.1.1
  json_annotation: ^4.3.0
  local_auth: ^2.1.2
  logger: ^1.0.0
  number_display: ^3.0.0
  package_info: ^2.0.2
  phone_number: 1.0.0
  pin_code_fields: ^8.0.1
  redux_dev_tools: ^0.7.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_thunk: ^0.4.0
  responsive_framework: ^1.1.0
  sentry_flutter: ^7.4.1
  share_plus: ^6.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.9
  web3dart: ^2.6.1
  webview_flutter: ^4.0.7
  youtube_explode_dart: ^1.12.4
  ethereum_addresses:
    git:
      url: https://github.com/fuseio/dart-ethereum_address.git
      ref: master
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  wallet_connect: ^1.0.4
  marketing_cards:
    path: ../../MarketingCards/marketing_cards
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
dependency_overrides:
  dio: ^5.1.1

dev_dependencies:
  auto_route_generator: ^6.0.3
  build_runner: ^2.0.6
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.1.6
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.5
  json_serializable: ^6.0.1
  lint: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/Peepl-Logos/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
    - family: PeeplIcons
      fonts:
        - asset: assets/fonts/PeeplIcons.ttf
  uses-material-design: true
