name: guide_liverpool
version: 1.7.0+33
publish_to: none
description: The Guide Liverpool app is a blog reader application for local news and updates in Liverpool
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  analyzer: ^4.7.0
  another_flushbar: ^1.12.29
  app_tracking_transparency: ^2.0.1
  auto_route: ^5.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  charge_wallet_sdk: ^0.0.2
  chewie: ^1.3.2
  confetti: ^0.7.0
  country_code_picker: ^2.0.2
  decimal: ^2.3.0
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flex_color_scheme: ^5.1.0
  flutter_dotenv: ^5.0.0
  flutter_html: ^3.0.0-alpha.3
  flutter_inappwebview: ^5.7.1
  flutter_localized_locales: ^2.0.2
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^6.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_stripe: ^5.1.0
  flutter_svg: ^1.1.5
  flutter_udid: ^2.0.0
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^0.13.4
  image_picker: ^0.8.6
  injectable: ^1.5.3
  json_annotation: ^4.3.0
  local_auth: ^2.1.2
  logger: ^1.0.0
  modal_bottom_sheet: ^2.1.2
  number_display: ^3.0.0
  package_info: ^2.0.2
  phone_number: ^1.0.0
  pin_code_fields: ^7.2.0
  redux_dev_tools: ^0.7.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_thunk: ^0.4.0
  responsive_framework: ^0.2.0
  sentry_flutter: ^6.17.0
  share_plus: ^4.0.4
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.9
  web3dart: ^2.3.5
  web_socket_channel: ^2.2.0
  webview_flutter: ^3.0.2
  youtube_explode_dart: ^1.10.8
  ethereum_addresses:
    git:
      url: https://github.com/fuseio/dart-ethereum_address.git
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1
  wallet_connect: ^1.0.4
  collection: ^1.16.0
dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.0.6
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.6
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  lint: ^1.5.3
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/Peepl-Logos/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
    - family: PeeplIcons
      fonts:
        - asset: assets/fonts/PeeplIcons.ttf
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en_US
