name: guide_liverpool
version: 1.1.0+20
publish_to: none
description: The Guide Liverpool app is a blog reader application for local news and updates in Liverpool
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  analyzer: ^3.4.1
  another_flushbar: ^1.10.24
  app_tracking_transparency: ^2.0.1
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  auto_size_text_field: ^2.0.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  chewie: ^1.3.2
  confetti: ^0.7.0
  contacts_service: ^0.6.1
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  decimal: ^2.0.0
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^11.2.6
  firebase_remote_config: ^2.0.5
  fl_chart: ^0.51.0
  flare_flutter: ^3.0.1
  flex_color_scheme: ^5.0.0
  flutter_cupertino_localizations: ^1.0.1
  flutter_dotenv: ^5.0.0
  flutter_html: ^3.0.0-alpha.3
  flutter_inappwebview: ^5.3.2
  flutter_localized_locales: ^2.0.2
  flutter_platform_widgets: ^1.9.5
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.2.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_stripe: ^2.5.0
  flutter_svg: ^1.0.3
  flutter_udid: ^2.0.0
  flutter_web_browser: ^0.17.1
  flutter_math_fork: ^0.6.2 #remove in newer flutter version, packaged for no reason with flutter 2.8
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  youtube_explode_dart: ^1.10.8
  xml: ^5.3.1
  google_maps_flutter: ^2.0.6
  grouped_list: ^5.1.1
  image_picker: ^0.8.2
  injectable: ^1.4.1
  json_annotation: ^4.3.0
  local_auth: ^2.0.0
  logger: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  number_display: ^3.0.0
  package_info: ^2.0.2
  permission_handler: ^9.2.0
  phone_number: ^0.12.0+1
  pin_code_fields: ^7.2.0
  plaid_flutter: ^2.1.3
  qr_flutter: ^4.0.0
  rate_my_app: ^1.1.0+1
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_thunk: ^0.4.0
  responsive_framework: ^0.2.0
  scan: ^1.4.3
  sentry_flutter: ^6.2.0
  share_plus: ^4.0.4
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.9
  webview_flutter: ^3.0.2
  wallet_core:
    git:
      url: https://github.com/fuseio/wallet_core.git
      ref: master
  ethereum_addresses:
    git:
      url: https://github.com/fuseio/dart-ethereum_address.git
      ref: master
  flutter_segment:
    git:
      url: https://github.com/fuseio/flutter-segment.git
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.0.6
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.1.6
  freezed: ^1.1.1
  injectable_generator: ^1.4.1
  json_serializable: ^6.0.1
  lint: ^1.5.3
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900

  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en_US
